name: Dlancer-Integration-Workflow

on:
  pull_request:
    branches: master

jobs:
  Fetch, Test & Merge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        fetch-depth: 0

    - name: Fetch Driver
      run: >-
        curl -s -o expEnv.py "https://raw.githubusercontent.com/Dlancer-org/Collaboration-scripts/master/expEnv.py";
        chmod +x expEnv.py;
        python3 expEnv.py --pr-title ${{ github.event.pull_request.title }};

    - name: Install dependencies
      run: <embedd-dependency-installer-while-project-creation>

    - name: Run tests
      run: echo $TEST_RUNNER
    
    - name: Commit Test Cases & Merge
      if: success()
      run: <Fetch && Run the script, which requests endpoint for commit and PR merge>  (Supply repo name, test cases, destination path, pr author, task id)

    
